title: "Enderpirl Launcher"
description: "Стильный и мощный лаунчер для Minecraft."
email: "m4212501@gmail.com"
url: ""
baseurl: ""
github_username: "EnderpirlTeam"
theme: minima

# Настройки навигации (раскомментируйте, если нужны кнопки в меню)
# header_pages:
#   - about.md

# Настройки соцсетей (раскомментируйте, если нужно)
# github_username: EnderpirlTeam
# twitter_username: ваш_логин

# Настройки сервера (опционально, для виджетов)
# server_ip: play.enderpirl.ru
# server_name: EnderpirlMine
