title: "EnderPirl Launcher"
description: "Стильный и мощный лаунчер для Minecraft."
email: "m4212501@gmail.com"
url: ""
baseurl: ""
github_username: "EnderpirlTeam"
theme: minima

# Настройки меню (для темы minima)
header_pages:
  - index.md
  - download.md
