title: "EnderPirl Launcher"
description: "Стильный и мощный лаунчер для Minecraft."
email: "m4212501@gmail.com"
url: ""
baseurl: ""
github_username: "EnderpirlTeam"
theme: minima

# ===== НАСТРОЙКИ МЕНЮ =====
header_pages:
  - index.md
  - download.md

# ===== НАСТРОЙКИ НАВИГАЦИИ =====
header_pages:
  - name: Главная
    url: /
  - name: Скачать
    url: /download
